INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("100","Literatura");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("101","Ciencias Politicas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("102","Musica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("103","Bellas Artes");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("104","Derecho");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("105","Educacion");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("106","Psicologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("107","Quimica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("108","Geologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("109","Biologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("110","Anatomia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("111","Fisiologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("112","Bacteriologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("113","Medicina");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("114","Botanica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("115","Zoologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("116","Agricultura");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("117","Farmacologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("118","Terapeutica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("119","Enfermeria");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("120","Osteopatia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("121","Historia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("122","Geografia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("123","Economia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("124","Administracion");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("125","Ciencia Militar");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("126","Ciencia Naval");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("127","Ciencias sociales");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("128","Comercio");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("129","Patologia Social");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("130","Comercio");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("131","Finanzas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("132","Tecnologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("133","Ciencia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("134","Matematicas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("135","Astronomia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("136","Fisica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("137","Bibliotecologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("138","Literatura");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("139","Ciencias Politicas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("140","Musica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("141","Bellas Artes");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("142","Derecho");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("143","Educacion");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("144","Psicologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("145","Quimica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("146","Geologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("147","Biologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("148","Anatomia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("149","Fisiologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("150","Bacteriologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("151","Medicina");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("152","Botanica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("153","Zoologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("154","Agricultura");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("155","Farmacologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("156","Terapeutica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("157","Enfermeria");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("158","Osteopatia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("159","Historia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("160","Geografia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("161","Economia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("162","Administracion");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("163","Ciencia Militar");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("164","Ciencia Naval");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("165","Ciencias sociales");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("166","Comercio");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("167","Patologia Social");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("168","Comercio");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("169","Finanzas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("170","Tecnologia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("171","Ciencia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("172","Matematicas");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("173","Astronomia");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("174","Fisica");
INSERT INTO `Materia` (`clave_materia`,`nombre`) VALUES ("175","Bibliotecologia");
